# ./.tmuxinator.yml

name: AUTO RACE 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: BehaviorTree
# startup_pane: 0

windows:
  - Gazebo: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch rom2109_gazebo simulation_race.launch.py open_rviz:=False use_sim_time:=True
  - AES_Break: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 run rom2109_race aes_run --ros-args -p ttc_final:=1.0
  - RUN: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 run rom2109_race linear_run --ros-args -p linear_speed:=2.0
  - PID: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; 
  - CLI: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; gnome-terminal -- ros2 run teleop_twist_keyboard teleop_twist_keyboard /cmd_vel:=/cmd_vel_keyboard
