# ./.tmuxinator.yml

name: ROM Dynamics 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: Gazebo
# startup_pane: 0

windows:
  - Gazebo: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; roslaunch rom2109_gazebo gazebo_simulation.launch
  - EKF: 
      root: ~/
      panes:
        - clear; #source ~/.bashrc; ros2 launch rom2109_gazebo ekf.launch.py publish_tf:=False use_sim_time:=True
  - SlamToolBox: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; #ros2 launch rom2109_nav2 online_async_launch_mapping_launch.py use_sim_time:=True
  - LittleSLAM: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; #ros2 launch rom2109_nav2 sim_navigation_launch.py map_subscribe_transient_local:=True use_sim_time:=True
  - Twist: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; #ros2 run teleop_twist_keyboard teleop_twist_keyboard /cmd_vel:=/cmd_vel_keyboard
  - CLI: 
      root: ~/
      panes:
        - source ~/.bashrc; clear; 
