twist_mux:
  ros__parameters:
    topics:

      # rom_aeb:
      #   topic: /aeb/cmd_vel 
      #   timeout: 3.0
      #   priority: 100
      linear:
        topic: linear_vel 
        timeout: 0.5
        priority: 10
      # pid:
      #   topic: pid_vel 
      #   timeout: 0.5
      #   priority: 20
      # aes:
      #   topic: brake      
      #   timeout: 0.5
      #   priority: 250
      keyboard: 
        topic: cmd_vel_keyboard
        timeout: 0.5
        priority: 100
