twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_collision_to_diff_cont # rviz goal
        timeout: 0.5
        priority: 10
      behavior:
        topic: cmd_vel_bhserver # behavior tree
        timeout: 0.5
        priority: 100
      #joystick:
        #topic: cmd_vel_joy # behavior tree
        #timeout: 0.5
        #priority: 100
